apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: us-central1-docker.pkg.dev/counter-427614/counter-app/counter-app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: artifact-registry-secret
