apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: gcr.io/counter-427614/counter-app:latest
        ports:
        - containerPort: 3000
